services:
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    environment:
      - SECRET_KEY=super-secret-change-me
      - TOKEN_EXPIRE_MINUTES=60
    ports:
      - "8001:8001"

  api-gateway:
    build:
      context: ./services/api-gateway
    container_name: api-gateway
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
