from app.infrastructure.pocketbase_base import PocketBaseClient
from app.infrastructure.repositories.lab_access_session_repository import LabAccessSessionRepository
from app.infrastructure.repositories.lab_block_repository import LabBlockRepository
from app.infrastructure.repositories.lab_reservation_repository import LabReservationRepository
from app.infrastructure.repositories.lab_schedule_repository import LabScheduleRepository
from app.infrastructure.repositories.reservation_support_repository import ReservationSupportRepository
from app.infrastructure.repositories.tutorial_session_repository import TutorialSessionRepository
from app.infrastructure.repositories.user_penalty_repository import UserPenaltyRepository

_pb_client = PocketBaseClient()

lab_reservation_repo = LabReservationRepository(_pb_client)
lab_schedule_repo = LabScheduleRepository(_pb_client)
lab_block_repo = LabBlockRepository(_pb_client)
tutorial_session_repo = TutorialSessionRepository(_pb_client, lab_reservation_repo)
user_penalty_repo = UserPenaltyRepository(_pb_client)
lab_access_session_repo = LabAccessSessionRepository()
reservation_support_repo = ReservationSupportRepository(_pb_client)
